export default {
  SET_COLOR_RED: 'SET_COLOR_RED',
  SET_COLOR_GREEN: 'SET_COLOR_GREEN',
  SET_COLOR_BLUE: 'SET_COLOR_BLUE',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_MANUAL_COLOR: 'SET_MANUAL_COLOR',
  SET_COLOR_HEX: 'SET_COLOR_HEX',
  SET_TEMPORARY_COLOR: 'SET_TEMPORARY_COLOR',
};